name: Smoke test gateway
description: Tests /v1/embeddings and /v1/responses endpoints with retries
inputs:
  gateway_url:
    required: true
    description: Gateway base URL (e.g. https://...azurecontainerapps.io)
  gateway_key:
    required: true
    description: AIGATEWAY_KEY for Authorization header
  embedding_model:
    required: true
    description: Embedding deployment name
  codex_model:
    required: true
    description: Codex model for responses endpoint
  max_attempts:
    required: false
    default: "5"
    description: Max retry attempts per endpoint
  retry_sleep:
    required: false
    default: "10"
    description: Seconds between retries
runs:
  using: composite
  steps:
    - name: Smoke test gateway (embeddings + responses)
      shell: bash
      env:
        GW: ${{ inputs.gateway_url }}
        GW_KEY: ${{ inputs.gateway_key }}
        EMB_MODEL: ${{ inputs.embedding_model }}
        CODEX_MODEL: ${{ inputs.codex_model }}
        SMOKE_MAX_ATTEMPTS: ${{ inputs.max_attempts }}
        SMOKE_RETRY_SLEEP: ${{ inputs.retry_sleep }}
      run: |
        set -euo pipefail
        echo "Gateway: ${GW}"

        if [[ "${GW_KEY}" =~ ^[Bb]earer[[:space:]]+.+$ ]]; then
          AUTH_HEADER_VALUE="${GW_KEY}"
        else
          AUTH_HEADER_VALUE="Bearer ${GW_KEY}"
        fi
        echo "Auth header mode: $([[ "${GW_KEY}" =~ ^[Bb]earer[[:space:]]+.+$ ]] && echo 'pass-through' || echo 'Bearer prefix')"

        MODELS_CODE=0

        fetch_models() {
          local models_code=0
          for attempt in $(seq 1 "${SMOKE_MAX_ATTEMPTS}"); do
            curl -sS -o /tmp/models.json -w "%{http_code}" \
              -X GET "${GW}/v1/models" \
              -H "Authorization: ${AUTH_HEADER_VALUE}" \
              > /tmp/models.code 2>/dev/null || true
            models_code=$(cat /tmp/models.code 2>/dev/null || echo "")
            [ -z "$models_code" ] || [[ ! "$models_code" =~ ^[0-9]+$ ]] && models_code=0
            if [ "$models_code" -ge 200 ] && [ "$models_code" -lt 300 ]; then
              MODELS_CODE="$models_code"
              return 0
            fi
            echo "Attempt ${attempt}/${SMOKE_MAX_ATTEMPTS}: /v1/models returned ${models_code}, retrying in ${SMOKE_RETRY_SLEEP}s..."
            sleep "${SMOKE_RETRY_SLEEP}"
          done
          MODELS_CODE="$models_code"
          return 1
        }

        dump_models_diagnostics() {
          echo "--- /v1/models diagnostics ---"
          echo "HTTP: ${MODELS_CODE}"
          if [ -s /tmp/models.json ]; then
            echo "Body (first 1200 chars):"
            head -c 1200 /tmp/models.json || true
            echo
          else
            echo "Body: <empty>"
          fi
          echo "-------------------------------"
        }

        probe_embedding_model() {
          local candidate="$1"
          local code=0
          curl -sS -o /tmp/emb_probe.json -w "%{http_code}" \
            -X POST "${GW}/v1/embeddings" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${AUTH_HEADER_VALUE}" \
            -d "{\"model\":\"${candidate}\",\"input\":\"smoke test\"}" \
            > /tmp/emb_probe.code 2>/dev/null || true
          code=$(cat /tmp/emb_probe.code 2>/dev/null || echo "")
          [ -z "$code" ] || [[ ! "$code" =~ ^[0-9]+$ ]] && code=0
          if [ "$code" -ge 200 ] && [ "$code" -lt 300 ]; then
            return 0
          fi
          return 1
        }

        resolve_effective_models() {
          EMB_EFFECTIVE="${EMB_MODEL}"
          CODEX_EFFECTIVE="${CODEX_MODEL}"

          if ! command -v jq >/dev/null 2>&1; then
            echo "jq not found; using requested models as-is."
            return 0
          fi

          jq -r '.data[]?.id // empty' /tmp/models.json | sed '/^$/d' > /tmp/models.ids || true
          if [ ! -s /tmp/models.ids ]; then
            echo "No models listed by /v1/models; using requested models as-is."
            dump_models_diagnostics
            return 0
          fi

          echo "Models returned by /v1/models:"
          head -n 30 /tmp/models.ids | sed 's/^/- /'

          if ! grep -Fxq "${EMB_MODEL}" /tmp/models.ids; then
            EMB_CANDIDATE=$(grep -Ei 'embed|embedding' /tmp/models.ids | head -n1 || true)
            if [ -n "${EMB_CANDIDATE:-}" ]; then
              EMB_EFFECTIVE="${EMB_CANDIDATE}"
              echo "Requested embedding model '${EMB_MODEL}' not available; using '${EMB_EFFECTIVE}'."
            fi
          fi

          if ! grep -Fxq "${CODEX_MODEL}" /tmp/models.ids; then
            RESP_CANDIDATE=$(grep -Eiv 'embed|embedding' /tmp/models.ids | head -n1 || true)
            if [ -n "${RESP_CANDIDATE:-}" ]; then
              CODEX_EFFECTIVE="${RESP_CANDIDATE}"
              echo "Requested responses model '${CODEX_MODEL}' not available; using '${CODEX_EFFECTIVE}'."
            fi
          fi

          echo "Using embedding model: ${EMB_EFFECTIVE}"
          echo "Using responses model: ${CODEX_EFFECTIVE}"
        }

        refine_embedding_with_probes() {
          : > /tmp/emb.candidates
          {
            echo "${EMB_EFFECTIVE:-}"
            echo "${EMB_MODEL}"
            echo "text-embedding-3-large"
            echo "text-embedding-3-small"
            echo "text-embedding-ada-002"
            if [ -s /tmp/models.ids ]; then
              grep -Ei 'embed|embedding' /tmp/models.ids || true
            fi
          } | sed '/^$/d' | awk '!seen[$0]++' > /tmp/emb.candidates

          while IFS= read -r candidate; do
            echo "Probing embedding candidate: ${candidate}"
            if probe_embedding_model "${candidate}"; then
              EMB_EFFECTIVE="${candidate}"
              echo "Selected embedding model from probe: ${EMB_EFFECTIVE}"
              return 0
            fi
          done < /tmp/emb.candidates

          echo "No embedding probe candidate succeeded; keeping '${EMB_EFFECTIVE}'."
          return 0
        }

        if fetch_models; then
          resolve_effective_models
        else
          echo "Unable to fetch /v1/models after retries; using requested models as-is."
          EMB_EFFECTIVE="${EMB_MODEL}"
          CODEX_EFFECTIVE="${CODEX_MODEL}"
          dump_models_diagnostics
        fi

        refine_embedding_with_probes

        echo "Testing /v1/embeddings..."
        EMB_CODE=0
        for attempt in $(seq 1 "${SMOKE_MAX_ATTEMPTS}"); do
          curl -sS -o /tmp/emb.json -w "%{http_code}" \
            -X POST "${GW}/v1/embeddings" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${AUTH_HEADER_VALUE}" \
            -d "{\"model\":\"${EMB_EFFECTIVE}\",\"input\":\"smoke test\"}" \
            > /tmp/emb.code 2>/dev/null || true
          EMB_CODE=$(cat /tmp/emb.code 2>/dev/null || echo "")
          [ -z "$EMB_CODE" ] || [[ ! "$EMB_CODE" =~ ^[0-9]+$ ]] && EMB_CODE=0
          if [ "$EMB_CODE" -ge 200 ] && [ "$EMB_CODE" -lt 300 ]; then
            break
          fi
          echo "Attempt ${attempt}/${SMOKE_MAX_ATTEMPTS}: embeddings returned ${EMB_CODE}, retrying in ${SMOKE_RETRY_SLEEP}s..."
          sleep "${SMOKE_RETRY_SLEEP}"
        done
        if [ "$EMB_CODE" -lt 200 ] || [ "$EMB_CODE" -ge 300 ]; then
          echo "Embeddings failed after ${SMOKE_MAX_ATTEMPTS} attempts (${EMB_CODE})" >&2
          cat /tmp/emb.json >&2 || true
          exit 1
        fi
        echo "Testing /v1/responses..."
        RESP_CODE=0
        for attempt in $(seq 1 "${SMOKE_MAX_ATTEMPTS}"); do
          curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -X POST "${GW}/v1/responses" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${AUTH_HEADER_VALUE}" \
            -d "{\"model\":\"${CODEX_EFFECTIVE}\",\"input\":\"Respond with exactly: OK\"}" \
            > /tmp/resp.code 2>/dev/null || true
          RESP_CODE=$(cat /tmp/resp.code 2>/dev/null || echo "")
          [ -z "$RESP_CODE" ] || [[ ! "$RESP_CODE" =~ ^[0-9]+$ ]] && RESP_CODE=0
          if [ "$RESP_CODE" -ge 200 ] && [ "$RESP_CODE" -lt 300 ]; then
            break
          fi
          echo "Attempt ${attempt}/${SMOKE_MAX_ATTEMPTS}: responses returned ${RESP_CODE}, retrying in ${SMOKE_RETRY_SLEEP}s..."
          sleep "${SMOKE_RETRY_SLEEP}"
        done
        if [ "$RESP_CODE" -lt 200 ] || [ "$RESP_CODE" -ge 300 ]; then
          echo "Responses failed after ${SMOKE_MAX_ATTEMPTS} attempts (${RESP_CODE})" >&2
          cat /tmp/resp.json >&2 || true
          exit 1
        fi
        echo "Smoke tests passed."
